schema_version = "1.0.0"

id = "batch_asset_placer"
name = "Batch Asset Placer"
tagline = "Adds selected assets from Asset Browser to 3D cursor"
version = "1.0.1"
type = "add-on"

blender_version_min = "4.5.0"

maintainer = "Andrey Pestryakov (3D Vopros)"
website = "https://vk.com/3dvopros"

tags = [
    "Import-Export"
]

license = ["SPDX:GPL-3.0-or-later"]
support_level = "COMMUNITY"
